{
  "id": "ch_C0516UPPMT3_2023-08-04_1691163736.698549_thread",
  "type": "channel",
  "channel_name": "aihub-feedback",
  "conversation_type": "thread",
  "participants": [
    "Tom",
    "Serena",
    "Dan H"
  ],
  "messages": [
    {
      "sender": "Dan H",
      "user_id": "U020E9AS9P0",
      "message": "Hello - Can we get \"Public Friendly\" Errors?  In my opinion there should never be a technical error on a public tool like AI Hub.  This occured when uploading a folder of docs.  When I reuploaded the doc, it worked fine.\n\nTLDR:\n• This error cannot be shown to the public\n• We shouldnt get this error at all",
      "time": "08:42",
      "timestamp": "1691163736.698549",
      "is_reply": false
    },
    {
      "sender": "Dan H",
      "user_id": "U020E9AS9P0",
      "message": "The error seems to happen consistently when uploading the whole file",
      "time": "08:42",
      "timestamp": "1691163778.996689",
      "is_reply": true
    },
    {
      "sender": "Tom",
      "user_id": "UUEDM4T9R",
      "message": "@Varun Jain this is super important imo from a UX perspective for the Commercial product",
      "time": "08:49",
      "timestamp": "1691164188.867249",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "@Dan H did you re-upload the doc individually, or did you re-upload the folder of docs?",
      "time": "09:08",
      "timestamp": "1691165288.366589",
      "is_reply": true
    },
    {
      "sender": "Dan H",
      "user_id": "U020E9AS9P0",
      "message": "If i re-upload individually, it seems to work.  When I tried the folder again, it failed again",
      "time": "09:08",
      "timestamp": "1691165315.540619",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "when you uploaded the folder, did the digitization job fail? or did the job succeed, and you later saw this “Error loading image” message?",
      "time": "09:09",
      "timestamp": "1691165354.711409",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "and yes, i agree we shouldn’t show technical errors in AI Hub\n\nin this case, there’s no reason to show the entire path for the image source\n\nhowever, in other cases, we should still try to provide a way for users to unblock themselves if they get an error",
      "time": "09:11",
      "timestamp": "1691165512.735459",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "i also think we need guidance from our docs team on our threshold for “technical errors”\n\nso far, every engineer just writes error messages according to their best judgment since we don’t have strict guidelines for what counts as a “technical error”",
      "time": "09:14",
      "timestamp": "1691165662.288289",
      "is_reply": true
    },
    {
      "sender": "Dan H",
      "user_id": "U020E9AS9P0",
      "message": "I'd love to see an error framework.  Many orgs i've worked with previously have a decision tree to guide how they serve errors, and templates for when they share info with the users",
      "time": "09:23",
      "timestamp": "1691166184.703769",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "completely agree! it’s a matter of prioritization since everyone’s working on new features, and things like error messages aren’t prioritized :sweat_smile:",
      "time": "09:31",
      "timestamp": "1691166701.498199",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C0516UPPMT3",
    "channel_name": "aihub-feedback",
    "date_file": "2023-08-04.json",
    "message_count": 10,
    "start_time": "1691163736.698549",
    "end_time": "1691166701.498199",
    "is_thread": true
  }
}