{
  "id": "ch_C0516UPPMT3_2023-12-20_1703067929.906559_thread",
  "type": "channel",
  "channel_name": "aihub-feedback",
  "conversation_type": "thread",
  "participants": [
    "Gauti",
    "Rakesh",
    "Hari",
    "Lee"
  ],
  "messages": [
    {
      "sender": "Lee",
      "user_id": "U01J31371LZ",
      "message": "Yes, object detection is on. Which i guess explains the reason.\n\n@Kerry do we have a timeline for when we’ll get source data with FR enabled? If its going to be a while I think we need to add a message to the config screen with a warning about the limitations.",
      "time": "02:25",
      "timestamp": "1703067929.906559",
      "is_reply": false
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "@Lee Can you try this in the internal sandbox?",
      "time": "02:26",
      "timestamp": "1703068010.266479",
      "is_reply": true
    },
    {
      "sender": "Lee",
      "user_id": "U01J31371LZ",
      "message": "@Hari is that this url? https://aihub-sandbox.internal.instabase.com/",
      "time": "02:27",
      "timestamp": "1703068074.121319",
      "is_reply": true
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "yes!! This is the one :+1::skin-tone-3:",
      "time": "02:28",
      "timestamp": "1703068128.415239",
      "is_reply": true
    },
    {
      "sender": "Lee",
      "user_id": "U01J31371LZ",
      "message": "I’m not able to open Converse in that environment",
      "time": "02:29",
      "timestamp": "1703068147.470819",
      "is_reply": true
    },
    {
      "sender": "Hari",
      "user_id": "UCX3XL72Q",
      "message": "Do you see any other workspace? Try your personal one if it show up..",
      "time": "02:29",
      "timestamp": "1703068195.007089",
      "is_reply": true
    },
    {
      "sender": "Lee",
      "user_id": "U01J31371LZ",
      "message": "If I switch to my personal, I can get into converse but digitisation fails",
      "time": "02:32",
      "timestamp": "1703068341.357439",
      "is_reply": true
    },
    {
      "sender": "Rakesh",
      "user_id": "U01668DGQCE",
      "message": "Hi Lee,\nThis is on aihub-sandbox ? There is a breaking change for aihub-sandbox we are investigating for indexing.",
      "time": "02:35",
      "timestamp": "1703068547.314529",
      "is_reply": true
    },
    {
      "sender": "Rakesh",
      "user_id": "U01668DGQCE",
      "message": "This should be fixed in next deploy.",
      "time": "02:40",
      "timestamp": "1703068840.736319",
      "is_reply": true
    },
    {
      "sender": "Rakesh",
      "user_id": "U01668DGQCE",
      "message": "@Lee I will let you know after that.\nFor object detection, we have provenance detection in progress - it will be completely enabled for all cases by 24.02 release.",
      "time": "02:41",
      "timestamp": "1703068900.707849",
      "is_reply": true
    },
    {
      "sender": "Lee",
      "user_id": "U01J31371LZ",
      "message": "Sounds great, thanks.",
      "time": "02:41",
      "timestamp": "1703068908.582179",
      "is_reply": true
    },
    {
      "sender": "Gauti",
      "user_id": "U01JA04CX1B",
      "message": "@Lee digitization issue of the internal sandbox is fixed now. You can try.",
      "time": "05:22",
      "timestamp": "1703078536.961259",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C0516UPPMT3",
    "channel_name": "aihub-feedback",
    "date_file": "2023-12-20.json",
    "message_count": 12,
    "start_time": "1703067929.906559",
    "end_time": "1703078536.961259",
    "is_thread": true
  }
}