{
  "id": "ch_CSY11CK7T_2025-05-21_1747850269.465909_thread",
  "type": "channel",
  "channel_name": "discuss-frontend",
  "conversation_type": "thread",
  "participants": [
    "Paul H",
    "Xindi Xu",
    "Serena",
    "ayesha.ali"
  ],
  "messages": [
    {
      "sender": "ayesha.ali",
      "user_id": "U058ZCMJ28L",
      "message": "hi team, the `review-manager-dashboard.spec.ts` cypress test is failing on uat due to an permission errors relating to retrieving deployments/deployment queues, i think specifically the user does not have access to the deployment. seems a bit weird, maybe a bug, maybe a cypress user role issue? @Xindi Xu\nCAT logs https://aihub-uat.internal.instabase.com/grafana/goto/ivyUsraNR?orgId=1\ncoreplatform logs: https://aihub-uat.internal.instabase.com/grafana/goto/Qc7qyr-Ng?orgId=1",
      "time": "10:57",
      "timestamp": "1747850269.465909",
      "is_reply": false
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "The cypress test uses the org admin, so it should have access to all these. lmk check the previous cypress runs\nhttps://github.com/instabase/instabase/blob/676d34fc9e8df1e65d6f643921b2973f370a88[…]ihub/__e2e__/Workspaces/Review/review-manager-dashboard.spec.ts (https://github.com/instabase/instabase/blob/676d34fc9e8df1e65d6f643921b2973f370a88fb/webserver/shared/src/js/webpacked/apps/src/aihub/__e2e__/Workspaces/Review/review-manager-dashboard.spec.ts#L41)",
      "time": "11:14",
      "timestamp": "1747851274.761899",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "So for this test in the past 7 days, the failure rate in CI is 10% (https://cloud.cypress.io/projects/cfhedy/analytics/top-failures?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22apps%2Fsrc%2Faihub%2F__e2e__%2FWorkspaces%2FReview%2Freview-manager-dashboard.spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%228de8b79a-cb28-b198-ce59-1e11bd2b08e3%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%7B%22disabled%22%3Afalse%2C%22label%22%3A%22ci%22%2C%22labelProperties%22%3A%7B%22color%22%3A%22%23dadade%22%7D%2C%22suggested%22%3Afalse%2C%22value%22%3A%22ci%22%7D%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222025-05-14%22%2C%22endDate%22%3A%222025-05-21%22%2C%22id%22%3A%22LAST_7_DAYS%22%7D&viewBy=TEST_CASE) but the failure rate in aihub-sandbox and aihub-uat is 100% (https://cloud.cypress.io/projects/cfhedy/analytics/top-failures?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22apps%2Fsrc%2Faihub%2F__e2e__%2FWorkspaces%2FReview%2Freview-manager-dashboard.spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%228de8b79a-cb28-b198-ce59-1e11bd2b08e3%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%7B%22disabled%22%3Afalse%2C%22label%22%3A%22aihub-uat%22%2C%22labelProperties%22%3A%7B%22color%22%3A%22%23dadade%22%7D%2C%22suggested%22%3Afalse%2C%22value%22%3A%22aihub-uat%22%7D%2C%7B%22disabled%22%3Afalse%2C%22label%22%3A%22aihub-sandbox-internal%22%2C%22labelProperties%22%3A%7B%22color%22%3A%22%23dadade%22%7D%2C%22suggested%22%3Afalse%2C%22value%22%3A%22aihub-sandbox-internal%22%7D%5D&tagsMatch=ANY&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222025-05-14%22%2C%22endDate%22%3A%222025-05-21%22%2C%22id%22%3A%22LAST_7_DAYS%22%7D&viewBy=TEST_CASE).",
      "time": "11:21",
      "timestamp": "1747851671.346029",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "Trace ID: d83ee4906a51302d\nhttps://aihub-uat.internal.instabase.com/grafana/explore?schemaVersion=1&panes=%7B%224fo%22:%[…]2visualisationType%22:%22logs%22%7D%7D%7D%7D&orgId=1 (https://aihub-uat.internal.instabase.com/grafana/explore?schemaVersion=1&panes=%7B%224fo%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22jaeger%22,%22uid%22:%22jaeger%22%7D,%22queryType%22:%22search%22,%22service%22:%22core-platform-service%22,%22operation%22:%22%2Frepo_service.RepoService%2FPopulateDocs%22%7D%5D,%22range%22:%7B%22from%22:%221747827819190%22,%22to%22:%221747841356514%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D,%223jv%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22query%22:%22d83ee4906a51302d%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221747827819190%22,%22to%22:%221747841356514%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D%7D&orgId=1)",
      "time": "11:27",
      "timestamp": "1747852024.888029",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "@ayesha.ali are you able to reproduce this thru the UI? Based on the failure rate in Cypress CI vs Cypress aihub-sandbox/uat, it seems like the code is working, but maybe the requestors' permission isn't correctly set",
      "time": "11:32",
      "timestamp": "1747852339.909119",
      "is_reply": true
    },
    {
      "sender": "ayesha.ali",
      "user_id": "U058ZCMJ28L",
      "message": "i get a successful deployment run using the support testing org admin user so looks like that's working, but getting failures in the ui with the cypress org admin enterprise user",
      "time": "14:39",
      "timestamp": "1747863560.006929",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "Can you share the email of the user where the deployment run is successful?",
      "time": "14:41",
      "timestamp": "1747863709.170839",
      "is_reply": true
    },
    {
      "sender": "ayesha.ali",
      "user_id": "U058ZCMJ28L",
      "message": "<mailto:support-testing+aihub-uat-internal-org-admin@instabase.com|support-testing+aihub-uat-internal-org-admin@instabase.com>\ndeployment: https://aihub-uat.internal.instabase.com/deployments/019105f9-6597-7f1f-a8a7-74da8f56a262/runs",
      "time": "14:42",
      "timestamp": "1747863748.963299",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "From the permission settings, `<mailto:support-testing+jenkins-org-admin-e@instabase.com|support-testing+jenkins-org-admin-e@instabase.com>` user has the same perms as `<mailto:support-testing+aihub-uat-internal-org-admin@instabase.com|support-testing+aihub-uat-internal-org-admin@instabase.com>`",
      "time": "14:46",
      "timestamp": "1747863971.661629",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "The Cypress test needs `cypress-human-review-deploymen` deployment. Runs are all failing after 5/20, but we have no runs from 5/12 to 5/20",
      "time": "14:50",
      "timestamp": "1747864222.572509",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "Just started another run using user `<mailto:support-testing+jenkins-org-admin-e@instabase.com|support-testing+jenkins-org-admin-e@instabase.com>`",
      "time": "14:52",
      "timestamp": "1747864337.052599",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "OK, that run failed with the same issue\n```\"Error while generating docs: Error occurred executing GRPC method: Request /repo_service.RepoService/PopulateDocs failed. Error code=INTERNAL, Error=(13, 'internal'), Message: Could not retrieve deployment's queue. Non-retriable error\"```",
      "time": "14:56",
      "timestamp": "1747864567.853679",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "Running deployment (https://aihub-uat.internal.instabase.com/deployments/018fc4f7-2bd5-79cc-b104-6f7036e259c7/configuration) with `<mailto:support-testing+aihubuat-orgadmin@instabase.com|support-testing+aihubuat-orgadmin@instabase.com>` works\nRunning deployment (https://aihub-uat.internal.instabase.com/deployments/01902cfe-bdc5-7d63-af10-b34314509995/configuration) with `<mailto:support-testing+jenkins-org-admin-e@instabase.com|support-testing+jenkins-org-admin-e@instabase.com>` failed\n\nI found that the deployment that works doesn't have review queues (the one on the left), while the one failed have review queues.",
      "time": "15:18",
      "timestamp": "1747865898.763239",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "the equivalent deployment on crafting-cyp (https://crafting-cyp.test.instabase.com/deployments/01902d1b-d641-7ec6-a2c8-7e51cd6c2ce7/configuration) also has review queues though?",
      "time": "15:20",
      "timestamp": "1747866009.729849",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "After I added review queues to the deployment that was working, it failed.",
      "time": "15:20",
      "timestamp": "1747866034.892099",
      "is_reply": true
    },
    {
      "sender": "ayesha.ali",
      "user_id": "U058ZCMJ28L",
      "message": "ahh okay yeah makes sense, i hsould have checked for that with <mailto:support-testing+aihubuat-orgadmin@instabase.com|support-testing+aihubuat-orgadmin@instabase.com>, the code path that's failing is when review queues do exist for a deployment",
      "time": "15:23",
      "timestamp": "1747866192.871489",
      "is_reply": true
    },
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "Trace of the success run, without review queues: f5330a127ebd8b4b (https://aihub-uat.internal.instabase.com/grafana/explore?schemaVersion=1&panes=%7B%224fo%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22jaeger%22,%22uid%22:%22jaeger%22%7D,%22queryType%22:%22search%22,%22service%22:%22core-platform-service%22,%22operation%22:%22%2Frepo_service.RepoService%2FPopulateDocs%22%7D%5D,%22range%22:%7B%22from%22:%221747827819000%22,%22to%22:%22now%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D,%224e1%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22query%22:%22f5330a127ebd8b4b%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221747827819000%22,%22to%22:%221747866093639%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D%7D&orgId=1)\nTrace of the failed run, with review queues: e530d3ce0f8d4b21 (https://aihub-uat.internal.instabase.com/grafana/explore?schemaVersion=1&panes=%7B%224fo%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22jaeger%22,%22uid%22:%22jaeger%22%7D,%22queryType%22:%22search%22,%22service%22:%22core-platform-service%22,%22operation%22:%22%2Frepo_service.RepoService%2FPopulateDocs%22%7D%5D,%22range%22:%7B%22from%22:%221747827819000%22,%22to%22:%22now%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D,%22kqu%22:%7B%22datasource%22:%22jaeger%22,%22queries%22:%5B%7B%22query%22:%22e530d3ce0f8d4b21%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221747827819000%22,%22to%22:%221747866093639%22%7D,%22panelsState%22:%7B%22logs%22:%7B%22id%22:%22A_1747841260503771239_c74f366a%22,%22visualisationType%22:%22logs%22%7D%7D%7D%7D&orgId=1)",
      "time": "15:27",
      "timestamp": "1747866461.584809",
      "is_reply": true
    },
    {
      "sender": "Serena",
      "user_id": "U01CZ3LBFU4",
      "message": "(i didn't mean to send my message to channel :facepalm: )",
      "time": "15:28",
      "timestamp": "1747866509.604129",
      "is_reply": true
    },
    {
      "sender": "Paul H",
      "user_id": "U011UPRAPNV",
      "message": "now i’m reading this thread because you did @Serena\n\n(after reading this thread, it seem y’all have a handle on things. I’ll leave now)",
      "time": "15:30",
      "timestamp": "1747866642.584639",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "CSY11CK7T",
    "channel_name": "discuss-frontend",
    "date_file": "2025-05-21.json",
    "message_count": 19,
    "start_time": "1747850269.465909",
    "end_time": "1747866642.584639",
    "is_thread": true
  }
}