{
  "id": "ch_C06FA6A23_2023-06-30_1688148374.842949_thread",
  "type": "channel",
  "channel_name": "discuss-engineering",
  "conversation_type": "thread",
  "participants": [
    "Xindi Xu",
    "Heymian",
    "Yiqing"
  ],
  "messages": [
    {
      "sender": "Xindi Xu",
      "user_id": "U03FT35MAHF",
      "message": "I had a PR failed on CI for an unrelated test:\nhttps://github.com/instabase/instabase/pull/43162\nhttps://jenkins.instabase.com/blue/organizations/jenkins/instabase/detail/PR-43162/4/pipeline\nI'll try rebuilding, but want to ask if we need to fix the test or any code related to this test.",
      "time": "11:06",
      "timestamp": "1688148374.842949",
      "is_reply": false
    },
    {
      "sender": "Heymian",
      "user_id": "UADQ9V8PK",
      "message": "@Yiqing is working on a fix",
      "time": "11:07",
      "timestamp": "1688148478.372089",
      "is_reply": true
    },
    {
      "sender": "Heymian",
      "user_id": "UADQ9V8PK",
      "message": "@Yiqing do you want to revert your change if this is going to take a bit of time to not block everyoneâ€™s pre-merges?",
      "time": "11:08",
      "timestamp": "1688148500.376169",
      "is_reply": true
    },
    {
      "sender": "Yiqing",
      "user_id": "U02T04U502J",
      "message": "i am waiting on the premerge for this PR: https://github.com/instabase/instabase/pull/43154",
      "time": "11:09",
      "timestamp": "1688148593.078169",
      "is_reply": true
    },
    {
      "sender": "Yiqing",
      "user_id": "U02T04U502J",
      "message": "@Xindi Xu I merged in the PR. The same test case can pass in my premerge",
      "time": "11:23",
      "timestamp": "1688149387.733479",
      "is_reply": true
    }
  ],
  "metadata": {
    "channel_id": "C06FA6A23",
    "channel_name": "discuss-engineering",
    "date_file": "2023-06-30.json",
    "message_count": 5,
    "start_time": "1688148374.842949",
    "end_time": "1688149387.733479",
    "is_thread": true
  }
}